#!/usr/bin/env python
# license removed for brevity
import rospy
import Adafruit_ADS1x15
import time

from std_msgs.msg import String
from bobelto_msg.msg import Adc

# ADS1015 ADC (12-bit) instance.
adc1 = Adafruit_ADS1x15.ADS1015()

# Note you can change the I2C address from its default (0x48), and/or the I2C
# bus by passing in these optional parameters:
adc1 = Adafruit_ADS1x15.ADS1015(address=0x49, busnum=1)

# Gain of 1 for reading voltages from 0 to 4.09V.
#  -   1 = +/-4.096V
GAIN = 1


def talker():

    pub = rospy.Publisher('adc_info', Adc, queue_size=5)
    rospy.init_node('ADC_pub', anonymuos=True)
    rate = rospy.Rate(10) # 10hz
    
    print('Reading ADS1x15 values, press Ctrl-C to quit...')
    print('| {0:>6} | {1:>6} | {2:>6} | {3:>6} |'.format(*range(4)))
    print('-' * 37)

    while not rospy.is_shutdown():

        msg = Adc()
        # values = [0]*4
        for i in range(4):
            # Read the specified ADC channel using the previously set gain value.
            #values[i] = adc.read_adc(i, gain=GAIN)
            msg[i] = adc.read_adc(i, gain=GAIN)
        # Print the ADC values.
        log_msg = '| {0:>6} | {1:>6} | {2:>6} | {3:>6} |'.format(*msg)
        # Pause for half a second.

        rospy.loginfo(log_msg)
        pub.publish(msg)
        rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass

