#!/usr/bin/env python
# license removed for brevity
import rospy
from std_msgs.msg import String

import time
import Adafruit_ADS1x15

# Or create an ADS1015 ADC (12-bit) instance.
adc = Adafruit_ADS1x15.ADS1015()

# Note you can change the I2C address from its default (0x48), and/or the I2C
# bus by passing in these optional parameters:
adc = Adafruit_ADS1x15.ADS1015(address=0x49, busnum=1)

# Gain of 1 for reading voltages from 0 to 4.09V.
#  -   1 = +/-4.096V
GAIN = 1


def talker():

    pub = rospy.Publisher('chatter', String, queue_size=30)
    rospy.init_node('ADC_pub', anonymous=True)
    rate = rospy.Rate(10) # 10hz

        print('Reading ADS1x15 values, press Ctrl-C to quit...')
        # Print nice channel column headers.
        print('| {0:>6} | {1:>6} | {2:>6} | {3:>6} |'.format(*range(4)))
        print('-' * 37)

    while not rospy.is_shutdown():

        values = [0]*4
        for i in range(4):
            # Read the specified ADC channel using the previously set gain value.
            values[i] = adc.read_adc(i, gain=GAIN)
        # Print the ADC values.
        values = '| {0:>6} | {1:>6} | {2:>6} | {3:>6} |'.format(*values)
        # Pause for half a second.

        rospy.loginfo(values)
        pub.publish(values)
        rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass

